### ISSUE TITLE
Incorrect result with incrementInteger

### ISSUE THREAD

**Issue by marcobambini** [darvelo/fractional-indexing-kotlin#1]
You incrementInteger function reports an incorrect result with x = "az" and digits = "0123456789".
According to the example in https://observablehq.com/@dgreensp/implementing-fractional-indexing the result should be "b00" and not "a0".

**Comment by darvelo** [comment]
@marcobambini It appears that just above that test in the article, the author switches from base10 to base62. I've run the tests with this in mind to check the result. If you change your digits to `"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"` you should see the correct result.

**Comment by marcobambini** [comment]
@darvelo oh yes you are right, thanks!

**Comment by marcobambini** [comment]
@darvelo do you think that the JS tests are sufficient? I was developing a C version and thinking about a way to expand the tests.

**Comment by darvelo** [comment]
@marcobambini I can't say with confidence, but more tests are always good for a library like this one. If you make an open-source C version I'd like to port any new tests you make over to this repo as well. :)
